sudo: false

language: node_js

node_js:
  - '8'

cache:
  directories:
    - node_modules

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

install:
  - npm i

script:
  - npm run lint:ci
  - npm run build:ci

git:
  depth: 1

notifications:
  slack: 
